import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { createRenderApiClient, getRenderErrorMessage } from "../../api/renderApi";
import { StatusBanner } from "../../components/StatusBanner";
import { useConnectivity } from "../../connectivity/ConnectivityProvider";
import { useLanguage } from "../../i18n/LanguageProvider";
import { useSession } from "../../session/SessionProvider";
import { radius, spacing } from "../../theme/tokens";
import { useTheme } from "../../theme/ThemeProvider";

export function ProfileScreen({ apiFactory = createRenderApiClient }) {
  const { isOnline } = useConnectivity(); const { identity } = useSession(); const { colors } = useTheme(); const { language, t } = useLanguage(); const styles = makeStyles(colors);
  const [password, setPassword] = useState(""); const [state, setState] = useState({ error: null, status: "idle" });
  const submit = async () => { if (!password.trim()) { setState({ error: { code: "profile.required" }, status: "error" }); return; } if (!isOnline || !identity) return; setState({ error: null, status: "loading" }); try { await apiFactory().changePassword({ userId: identity.id, newPassword: password }); setPassword(""); setState({ error: null, status: "success" }); } catch (error) { setPassword(""); setState({ error, status: "error" }); } };
  const message = state.error?.code === "profile.required" ? t("profile.required") : getRenderErrorMessage(state.error, language);
  return <View style={styles.screen}>{!isOnline ? <StatusBanner status="offline" /> : null}<ScrollView contentContainerStyle={styles.content}><Text style={styles.eyebrow}>{t("profile.eyebrow")}</Text><Text accessibilityRole="header" style={styles.title}>{t("profile.title")}</Text><Text style={styles.description}>{t("profile.description")}</Text><View accessibilityRole="summary" accessibilityLabel={t("profile.identity")} style={styles.identity}><View style={styles.rail} /><View style={styles.identityCopy}><Text style={styles.name}>{identity?.name}</Text><Text style={styles.email}>{identity?.email}</Text><Text style={styles.role}>{identity?.role?.name || t("profile.noRole")}</Text></View></View><View style={styles.form}><Text style={styles.formTitle}>{t("profile.change")}</Text><Text style={styles.help}>{t("profile.help")}</Text><Text style={styles.label}>{t("profile.password")}</Text><TextInput accessibilityLabel={t("profile.password")} autoCapitalize="none" autoCorrect={false} onChangeText={setPassword} secureTextEntry style={styles.input} value={password} /><Pressable accessibilityRole="button" accessibilityLabel={t("profile.submit")} disabled={!isOnline || state.status === "loading"} onPress={submit} style={[styles.button, (!isOnline || state.status === "loading") && styles.disabled]}><Text style={styles.buttonText}>{t("profile.submit")}</Text></Pressable>{state.status === "error" ? <Text accessibilityRole="alert" style={styles.error}>{message}</Text> : null}{state.status === "success" ? <Text accessibilityRole="alert" style={styles.success}>{t("profile.success")}</Text> : null}</View></ScrollView></View>;
}

const makeStyles = (colors) => StyleSheet.create({ screen: { backgroundColor: colors.canvas, flex: 1 }, content: { gap: spacing.card, padding: spacing.section }, eyebrow: { color: colors.action, fontSize: 12, fontWeight: "800", letterSpacing: 1.2 }, title: { color: colors.brand, fontSize: 30, fontWeight: "700", marginTop: -6 }, description: { color: colors.textSecondary, fontSize: 16, lineHeight: 23, marginTop: -8 }, identity: { backgroundColor: colors.surfaceRaised, borderColor: colors.borderSoft, borderRadius: radius.card, borderWidth: 1, flexDirection: "row", overflow: "hidden" }, rail: { backgroundColor: colors.brand, width: 12 }, identityCopy: { gap: spacing.micro, padding: spacing.card }, name: { color: colors.ink, fontSize: 20, fontWeight: "700" }, email: { color: colors.textSecondary, fontSize: 15 }, role: { color: colors.action, fontSize: 13, fontWeight: "800" }, form: { backgroundColor: colors.surface, borderColor: colors.borderSoft, borderRadius: radius.card, borderWidth: 1, gap: spacing.control, padding: spacing.card }, formTitle: { color: colors.ink, fontSize: 19, fontWeight: "700" }, help: { color: colors.textSecondary, fontSize: 14, lineHeight: 20 }, label: { color: colors.ink, fontSize: 14, fontWeight: "700" }, input: { backgroundColor: colors.control, borderColor: colors.borderSoft, borderRadius: radius.control, borderWidth: 1, color: colors.ink, fontSize: 16, minHeight: 48, paddingHorizontal: spacing.control }, button: { alignItems: "center", backgroundColor: colors.action, borderRadius: radius.control, justifyContent: "center", minHeight: 48 }, buttonText: { color: colors.onBrand, fontWeight: "800" }, disabled: { opacity: 0.45 }, error: { color: colors.danger, fontWeight: "700" }, success: { color: colors.success, fontWeight: "700" } });
